# Generated by Django 5.1.7 on 2025-03-18 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiVarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="chai/images")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "Masala Chai"),
                            ("KL", "Kadak Chai"),
                            ("CL", "Chai Latte"),
                            ("CL", "Green Chai"),
                            ("BL", "Black Chai"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
