# Generated by Django 5.1.7 on 2025-03-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
