# Generated by Django 5.1.7 on 2025-03-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0003_chaicertificate_chaireview_store"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Store",
            new_name="ChaiStore",
        ),
        migrations.RenameField(
            model_name="chaistore",
            old_name="chai_varities",
            new_name="chai_varieties",
        ),
    ]
